             np.sort

Return a sorted copy of an array


In [1]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[81, 19, 19, 56],
       [89, 40, 50, 56],
       [44, 65, 35, 99],
       [60, 46, 57, 48],
       [51, 20, 55, 25],
       [85, 82, 12, 60]], dtype=int32)

In [3]:
np.sort(a)

array([ 5, 19, 21, 43, 50, 58, 64, 66, 70, 77, 88, 89, 91, 97, 99],
      dtype=int32)

In [4]:
np.sort(b,axis=0)

array([[44, 19, 12, 25],
       [51, 20, 19, 48],
       [60, 40, 35, 56],
       [81, 46, 50, 56],
       [85, 65, 55, 60],
       [89, 82, 57, 99]], dtype=int32)

np.append

The numpy.append() appends valus along the mentioned axis at the end of the array

In [5]:
# code
np.append(a,200)

array([ 19,  89,  50,  97,  58,   5,  77,  21,  91,  43,  70,  99,  64,
        66,  88, 200])

In [6]:
b


array([[81, 19, 19, 56],
       [89, 40, 50, 56],
       [44, 65, 35, 99],
       [60, 46, 57, 48],
       [51, 20, 55, 25],
       [85, 82, 12, 60]], dtype=int32)

In [7]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[81., 19., 19., 56.,  1.],
       [89., 40., 50., 56.,  1.],
       [44., 65., 35., 99.,  1.],
       [60., 46., 57., 48.,  1.],
       [51., 20., 55., 25.,  1.],
       [85., 82., 12., 60.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [8]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique

with the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method


In [10]:
# code
e = np.array([11,22,2,2,3,3,5,6,9,4,8,8,8,0])

In [11]:
np.unique(e)

array([ 0,  2,  3,  4,  5,  6,  8,  9, 11, 22])

np.expand_dms

with the help Numpy.expand_dims() method, we can get the expanded dimension of an array


In [12]:
# code
a
a.shape

(15,)

In [13]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [14]:
np.expand_dims(a,axis=1)

array([[19],
       [89],
       [50],
       [97],
       [58],
       [ 5],
       [77],
       [21],
       [91],
       [43],
       [70],
       [99],
       [64],
       [66],
       [88]], dtype=int32)

np.where

The numpy.where() function return the indices of elements in an input array where the given condition is satisfied

In [15]:
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [16]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  4,  6,  8, 10, 11, 12, 13, 14]),)

In [17]:
# replace aall values >50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

array([19,  0, 50,  0,  0,  5,  0, 21,  0, 43,  0,  0,  0,  0,  0],
      dtype=int32)

In [18]:
np.where(a %2 ==0,0,a)

array([19, 89,  0, 97,  0,  5, 77, 21, 91, 43,  0, 99,  0,  0,  0],
      dtype=int32)

np.argmax

The numpy.argmax() function return indices of the max element of the array in a particular axis

In [19]:
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [20]:
np.argmax(a)

np.int64(11)

In [21]:
b

array([[81, 19, 19, 56],
       [89, 40, 50, 56],
       [44, 65, 35, 99],
       [60, 46, 57, 48],
       [51, 20, 55, 25],
       [85, 82, 12, 60]], dtype=int32)

In [22]:
np.argmax(b,axis=0)

array([1, 5, 3, 2])

In [23]:
np.argmax(b,axis=1)

array([0, 0, 3, 0, 2, 0])

In [24]:
# np.argmin
np.argmin(a)

np.int64(5)

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [25]:
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [26]:
np.cumsum(a)

array([ 19, 108, 158, 255, 313, 318, 395, 416, 507, 550, 620, 719, 783,
       849, 937])

In [27]:
b

array([[81, 19, 19, 56],
       [89, 40, 50, 56],
       [44, 65, 35, 99],
       [60, 46, 57, 48],
       [51, 20, 55, 25],
       [85, 82, 12, 60]], dtype=int32)

In [28]:
np.cumsum(b)

array([  81,  100,  119,  175,  264,  304,  354,  410,  454,  519,  554,
        653,  713,  759,  816,  864,  915,  935,  990, 1015, 1100, 1182,
       1194, 1254])

In [29]:
np.cumsum(b,axis=1)

array([[ 81, 100, 119, 175],
       [ 89, 129, 179, 235],
       [ 44, 109, 144, 243],
       [ 60, 106, 163, 211],
       [ 51,  71, 126, 151],
       [ 85, 167, 179, 239]])

In [30]:
# np.cumprod

np.cumprod(a)

array([                  19,                 1691,                84550,
                    8201350,            475678300,           2378391500,
               183136145500,        3845859055500,      349973174050500,
          15048846484171500,  1053419253892005000, -6391958306948814696,
       -3256962023114004992,  6401435358990289920, -8522754693850587136])

np.percentile

numpy.percentile() function used to compute the nth percentile of the given data along the specificed axis

In [31]:
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [32]:
np.percentile(a,50)

np.float64(66.0)

In [33]:
np.median(a)

np.float64(66.0)

np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of the data distribution in the graphical form


In [34]:
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [35]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 1, 0, 1, 2, 2, 2, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [36]:
np.histogram(a,bins=[0,50,100])

(array([ 4, 11]), array([  0,  50, 100]))

np.corrcoef
 

Return person product-moment correlation coefficients.

In [37]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

with the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.


In [39]:
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [ ]:
items = [10,20,30,6,40,5]

np.isin(a,items)
# which element is present 
a[np.isin(a,items)]

array([5], dtype=int32)

np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [43]:
a

array([19, 89, 50, 97, 58,  5, 77, 21, 91, 43, 70, 99, 64, 66, 88],
      dtype=int32)

In [44]:
np.flip(a)

array([88, 66, 64, 99, 70, 43, 91, 21, 77,  5, 58, 97, 50, 89, 19],
      dtype=int32)

In [45]:
b

array([[81, 19, 19, 56],
       [89, 40, 50, 56],
       [44, 65, 35, 99],
       [60, 46, 57, 48],
       [51, 20, 55, 25],
       [85, 82, 12, 60]], dtype=int32)

In [46]:
np.flip(b)

array([[60, 12, 82, 85],
       [25, 55, 20, 51],
       [48, 57, 46, 60],
       [99, 35, 65, 44],
       [56, 50, 40, 89],
       [56, 19, 19, 81]], dtype=int32)

In [47]:
np.flip(b,axis=0)

array([[85, 82, 12, 60],
       [51, 20, 55, 25],
       [60, 46, 57, 48],
       [44, 65, 35, 99],
       [89, 40, 50, 56],
       [81, 19, 19, 56]], dtype=int32)

np.put 

The numpy.put() function replaces specific elements of an array with give values of p_array. Array indexed works on flattened array.

In [51]:
a

array([100, 200,  50,  97,  58,   5,  77,  21,  91,  43,  70,  99,  64,
        66,  88], dtype=int32)

In [50]:
np.put(a,[0,1],[100,200])

np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned aixis.

In [52]:
np.delete(a,0)

array([200,  50,  97,  58,   5,  77,  21,  91,  43,  70,  99,  64,  66,
        88], dtype=int32)

In [53]:
np.delete(a,[1,2,3])

array([100,  58,   5,  77,  21,  91,  43,  70,  99,  64,  66,  88],
      dtype=int32)

Set function

. np.union1d,
. np.intersect1d,
. np.setdiff1d,
. np.setxor1d,
. np.in11d

In [54]:
m = np.array([1,2,3,4,5])
n = np.array([4,5,6,7,8])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
np.intersect1d(m,n)

array([4, 5])

In [56]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [57]:
np.setdiff1d(n,m)

array([6, 7, 8])

In [58]:
np.setxor1d(m,n)

array([1, 2, 3, 6, 7, 8])

In [59]:
np.in1d(m,1)

C:\Users\rahul\AppData\Local\Temp\ipykernel_20720\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

In [60]:
m[np.in1d(m,1)]

C:\Users\rahul\AppData\Local\Temp\ipykernel_20720\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

In [61]:
a

array([100, 200,  50,  97,  58,   5,  77,  21,  91,  43,  70,  99,  64,
        66,  88], dtype=int32)

In [62]:
np.clip(a,min=25,max=75)

array([75, 75, 50, 75, 58, 25, 75, 25, 75, 43, 70, 75, 64, 66, 75],
      dtype=int32)