Numpy array vs Python lists

In [1]:
# speed
# list
a = [i for i in range(10000000)]
b = [i for i in range(1000000,20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i]+ b[i])
    
print(time.time()-start)
  

1.8429484367370605


In [2]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c= a+b
print(time.time()-start)

0.132188081741333


In [5]:
1.8429484367370605/0.132188081741333

13.94186535169911

In [6]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [9]:
a = np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

Advance Indexing

In [15]:
# Normal Indexing and slicing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a[1,2]

np.int64(6)

In [17]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [18]:
# Fancy Indexing
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
a[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [21]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [26]:
# Boolean Indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[79, 87, 71, 38],
       [26,  6, 32, 55],
       [68, 60, 63, 74],
       [53, 52,  9, 50],
       [53,  8, 29, 87],
       [48, 92, 34, 93]], dtype=int32)

In [28]:
# find all number greater than 50
a[a>50]

array([79, 87, 71, 55, 68, 60, 63, 74, 53, 52, 53, 87, 92, 93],
      dtype=int32)