    np.sort

Return a sorted copy of an array


In [60]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([77, 44, 22, 56, 50, 35, 85, 56, 55, 94, 29, 66,  5, 31, 27])

In [61]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[22, 72, 34, 35],
       [38, 17, 66, 63],
       [99, 99, 54, 30],
       [46, 74, 67, 63],
       [24, 97, 11, 10],
       [ 8, 55,  3, 43]])

In [62]:
np.sort(a)

array([ 5, 22, 27, 29, 31, 35, 44, 50, 55, 56, 56, 66, 77, 85, 94])

In [63]:
np.sort(b,axis=1)

array([[22, 34, 35, 72],
       [17, 38, 63, 66],
       [30, 54, 99, 99],
       [46, 63, 67, 74],
       [10, 11, 24, 97],
       [ 3,  8, 43, 55]])

np.append

The numpy.append() appends valus along the mentioned axis at the end of the array

In [64]:
# code
np.append(a,200)

array([ 77,  44,  22,  56,  50,  35,  85,  56,  55,  94,  29,  66,   5,
        31,  27, 200])

In [65]:
b


array([[22, 72, 34, 35],
       [38, 17, 66, 63],
       [99, 99, 54, 30],
       [46, 74, 67, 63],
       [24, 97, 11, 10],
       [ 8, 55,  3, 43]])

In [66]:
# np.ones()
np.ones((b.shape[0],2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [67]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[22., 72., 34., 35.,  1.],
       [38., 17., 66., 63.,  1.],
       [99., 99., 54., 30.,  1.],
       [46., 74., 67., 63.,  1.],
       [24., 97., 11., 10.,  1.],
       [ 8., 55.,  3., 43.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [68]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [69]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique

with the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method


In [70]:
# code
e = np.array([11,22,2,2,3,3,5,6,9,4,8,8,8,0])

In [71]:
np.unique(e)

array([ 0,  2,  3,  4,  5,  6,  8,  9, 11, 22])

np.expand_dms

with the help Numpy.expand_dims() method, we can get the expanded dimension of an array


In [72]:
# code
a
a.shape

(15,)

In [73]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [74]:
np.expand_dims(a,axis=1)

array([[77],
       [44],
       [22],
       [56],
       [50],
       [35],
       [85],
       [56],
       [55],
       [94],
       [29],
       [66],
       [ 5],
       [31],
       [27]])

np.where

The numpy.where() function return the indices of elements in an input array where the given condition is satisfied

In [75]:
# find all indices with value greater than 50
a = np.random.randint(1,100,15)
print(a)
np.where(a>50)

a[np.where(a>50)]

[25 54 38 35 57 73 82  5  8 37 78 90 45 56  6]


array([54, 57, 73, 82, 78, 90, 56])

In [76]:
# replace all values >50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

array([25,  0, 38, 35,  0,  0,  0,  5,  8, 37,  0,  0, 45,  0,  6])

In [77]:
np.where(a %2 ==0,0,a)

array([25,  0,  0, 35, 57, 73,  0,  5,  0, 37,  0,  0, 45,  0,  0])

np.argmax

The numpy.argmax() function return indices of the max element of the array in a particular axis

In [78]:
a

array([25, 54, 38, 35, 57, 73, 82,  5,  8, 37, 78, 90, 45, 56,  6])

In [79]:
np.argmax(a)

11

In [80]:
b

array([[22, 72, 34, 35],
       [38, 17, 66, 63],
       [99, 99, 54, 30],
       [46, 74, 67, 63],
       [24, 97, 11, 10],
       [ 8, 55,  3, 43]])

In [81]:
np.argmax(b,axis=0)

array([2, 2, 3, 1], dtype=int64)

In [82]:
np.argmax(b,axis=1)

array([1, 2, 0, 1, 1, 1], dtype=int64)

In [83]:
# np.argmin
np.argmin(a)

7

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [84]:
a

array([25, 54, 38, 35, 57, 73, 82,  5,  8, 37, 78, 90, 45, 56,  6])

In [85]:
np.cumsum(a)

array([ 25,  79, 117, 152, 209, 282, 364, 369, 377, 414, 492, 582, 627,
       683, 689])

In [86]:
b

array([[22, 72, 34, 35],
       [38, 17, 66, 63],
       [99, 99, 54, 30],
       [46, 74, 67, 63],
       [24, 97, 11, 10],
       [ 8, 55,  3, 43]])

In [87]:
np.cumsum(b)

array([  22,   94,  128,  163,  201,  218,  284,  347,  446,  545,  599,
        629,  675,  749,  816,  879,  903, 1000, 1011, 1021, 1029, 1084,
       1087, 1130])

In [88]:
np.cumsum(b,axis=1)

array([[ 22,  94, 128, 163],
       [ 38,  55, 121, 184],
       [ 99, 198, 252, 282],
       [ 46, 120, 187, 250],
       [ 24, 121, 132, 142],
       [  8,  63,  66, 109]])

In [89]:
# np.cumprod
print(a)
np.cumprod(a)

[25 54 38 35 57 73 82  5  8 37 78 90 45 56  6]


array([         25,        1350,       51300,     1795500,   102343500,
       -1118859092, -1552132328,   829272952, -1955750976,   651657920,
        -710289792,   498428160,   954430720,  1908512768, -1433825280])

np.percentile

numpy.percentile() function used to compute the nth percentile of the given data along the specificed axis

In [90]:
a

array([25, 54, 38, 35, 57, 73, 82,  5,  8, 37, 78, 90, 45, 56,  6])

In [91]:
np.percentile(a,50)

45.0

In [92]:
np.median(a)

45.0

np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of the data distribution in the graphical form


In [93]:
a

array([25, 54, 38, 35, 57, 73, 82,  5,  8, 37, 78, 90, 45, 56,  6])

In [94]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 0, 1, 3, 1, 3, 0, 2, 1, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [95]:
np.histogram(a,bins=[0,50,100])

(array([8, 7], dtype=int64), array([  0,  50, 100]))

np.corrcoef
 

Return person product-moment correlation coefficients.

In [96]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

with the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.


In [97]:
a

array([25, 54, 38, 35, 57, 73, 82,  5,  8, 37, 78, 90, 45, 56,  6])

In [118]:
items = [10,20,30,6,40,5]

np.isin(a,items)
# which element is present 
a[np.isin(a,items)]

array([5, 6])

np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [99]:
a

array([25, 54, 38, 35, 57, 73, 82,  5,  8, 37, 78, 90, 45, 56,  6])

In [100]:
np.flip(a)

array([ 6, 56, 45, 90, 78, 37,  8,  5, 82, 73, 57, 35, 38, 54, 25])

In [101]:
b

array([[22, 72, 34, 35],
       [38, 17, 66, 63],
       [99, 99, 54, 30],
       [46, 74, 67, 63],
       [24, 97, 11, 10],
       [ 8, 55,  3, 43]])

In [102]:
np.flip(b)

array([[43,  3, 55,  8],
       [10, 11, 97, 24],
       [63, 67, 74, 46],
       [30, 54, 99, 99],
       [63, 66, 17, 38],
       [35, 34, 72, 22]])

In [103]:
np.flip(b,axis=0)

array([[ 8, 55,  3, 43],
       [24, 97, 11, 10],
       [46, 74, 67, 63],
       [99, 99, 54, 30],
       [38, 17, 66, 63],
       [22, 72, 34, 35]])

np.put 

The numpy.put() function replaces specific elements of an array with give values of p_array. Array indexed works on flattened array.

In [104]:
a

array([25, 54, 38, 35, 57, 73, 82,  5,  8, 37, 78, 90, 45, 56,  6])

In [121]:
# np.put(array, indices, values)
np.put(a,[0,1],[100,200])
a

array([100, 200,  38,  35,  57,  73,  82,   5,   8,  37,  78,  90,  45,
        56,   6])

np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned aixis.

In [106]:
np.delete(a,0)

array([200,  38,  35,  57,  73,  82,   5,   8,  37,  78,  90,  45,  56,
         6])

In [107]:
np.delete(a,[1,2,3])

array([100,  57,  73,  82,   5,   8,  37,  78,  90,  45,  56,   6])

Set function

. np.union1d,
. np.intersect1d,
. np.setdiff1d,
. np.setxor1d,
. np.in11d

In [108]:
m = np.array([1,2,3,4,5])
n = np.array([4,5,6,7,8])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
np.intersect1d(m,n)

array([4, 5])

In [110]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [111]:
np.setdiff1d(n,m)

array([6, 7, 8])

In [112]:
np.setxor1d(m,n)

array([1, 2, 3, 6, 7, 8])

In [113]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [114]:
m[np.in1d(m,1)]

array([1])

np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

In [122]:
a

array([100, 200,  38,  35,  57,  73,  82,   5,   8,  37,  78,  90,  45,
        56,   6])

In [116]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 38, 35, 57, 73, 75, 25, 25, 37, 75, 75, 45, 56, 25])