What is numpy?

Numpy is the fundamental package for scientific computing in python. it is a python library that provides a multidimensional array object,various derived object(such as masked array and matrices),and an assortment of routines for fast operations on arrays,including mathematical,logical,shape manipulation,sorting,selecting, I/O , discrete Fourier transforms, basic linear algebra, basic statistical operatons, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional array of homogeneous data types 

### Numpy Arrays vs Python Sequences
- Numpy arrays have a fixed size at creation, unlike python lists(which can grow dynamically). changing the size of an ndarray will create a new array and delete the original.

- The element in a Numpy array are all required to be of the same data type, and thus will be the same size in memory.

- Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. typically, such operations are executed more efficiently and with less code than is possible using python's built-in sequences.

- A growing plethora of scientific and mathematical python-based package are using numpy arrays, through these typically support python-sequence input, they convert such input to numpy array prior to processing, and they often output Numpy arrays.

In [1]:
# np.array
# 1 D Array (Vector)
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D (matrices)
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# you can called it tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,5,8]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 5 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
# np.arange(1,11)

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:

# with reshape
# np.arange(1,13)
# np.arange(1,13).reshape(4,3) # 2D array 
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [7]:
# np.ones np.zeros
np.ones((3,4))    # it is used to initilize the array
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# np.random

# np.random.random(4)
np.random.random((3,4))

array([[0.84625316, 0.68029176, 0.27364109, 0.41134424],
       [0.37410486, 0.00554611, 0.55643735, 0.3907344 ],
       [0.88153625, 0.76105713, 0.56961495, 0.0692778 ]])

In [78]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [79]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [80]:
a1 = np.arange(10) # vector
a2=np.arange(12,dtype=float).reshape(3,4) # matrices
a3 = np.arange(8).reshape(2,2,2) # 3d tensor

In [83]:
a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [88]:
# ndim
a3.ndim

3

In [90]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [93]:
# size
a3.size

8

In [95]:
# itemsize - it tell each and every item take 
# how much space in memory.
a2.itemsize

8

In [17]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


Changing Datatype

In [96]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [97]:
a3.itemsize

4

Array Operations

In [19]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
# scaler operations

# arthematic
a1*2
# a1 / 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [21]:
# relational 
a2 > 5
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [22]:
# vector operations
# arthematic
a1 + a2 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions

In [23]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[18., 24., 99.],
       [82., 21., 97.],
       [62., 91., 96.]])

In [24]:
# min/max/sum/prod
# 0 -> col and 1-> row
np.max(a1)
np.sum(a1)
np.prod(a1)
np.max(a1,axis =0) # you can use axis in every function

array([82., 91., 99.])

In [25]:
# mean/median/std/var
np.mean(a1, axis = 1)
np.median(a1)
np.std(a1)
np.var(a1,axis=0)

array([ 714.66666667, 1044.22222222,    1.55555556])

In [26]:
# trignometric function
np.sin(a1)

array([[-0.75098725, -0.90557836, -0.99920683],
       [ 0.31322878,  0.83665564,  0.37960774],
       [-0.7391807 ,  0.10598751,  0.98358775]])

In [27]:
# dot product [2,3][3,2]
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [28]:
# log and exponents
np.log(a1)
np.exp(a1)

C:\Users\rahul\AppData\Local\Temp\ipykernel_11008\1488485187.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [29]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)



array([[ 8., 68.,  7.],
       [85.,  5., 31.]])

Indexing and Slicing

In [30]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1[-1]

9

In [33]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a2[1,2]

6

In [35]:
a2[2,3]


11

In [36]:
a2[1,0]

4

In [37]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
a3[1,0,1]

5

In [39]:
a3[0,1,1]

3

In [40]:
a3[0,0,0]

0

In [41]:
# start the slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1[2:5]

array([2, 3, 4])

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
# first is column and second is row
a2[0,:]

array([0, 1, 2, 3])

In [45]:
a2[:,2]

array([ 2,  6, 10])

In [46]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [47]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [48]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [49]:
a2[1,::3]

array([4, 7])

In [50]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [51]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [53]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [54]:
a3[0,1,:]

array([3, 4, 5])

In [55]:
a3[1,:,1]

array([10, 13, 16])

In [56]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [57]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [58]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [62]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [63]:
for i in a3:
    print(i)    

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [64]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [65]:
# reshape
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [67]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [68]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [70]:
# horizontal stacking
a4=np.arange(12).reshape(3, 4)
a5=np.arange(12,24).reshape(3, 4)
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [71]:
np.hstack((a4, a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [72]:
# vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [73]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [75]:
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [76]:
# vertical splitting
np.vsplit(a4, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]