             np.sort

Return a sorted copy of an array


In [1]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([48, 29, 27, 20, 38, 89, 63, 79, 13, 89, 38,  6, 68, 83, 49],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[34, 85, 87, 22],
       [87,  8, 88,  4],
       [16, 56, 15, 36],
       [31, 91, 51, 90],
       [80, 54, 93,  3],
       [67, 56, 79,  5]], dtype=int32)

In [3]:
np.sort(a)

array([ 6, 13, 20, 27, 29, 38, 38, 48, 49, 63, 68, 79, 83, 89, 89],
      dtype=int32)

In [4]:
np.sort(b,axis=0)

array([[16,  8, 15,  3],
       [31, 54, 51,  4],
       [34, 56, 79,  5],
       [67, 56, 87, 22],
       [80, 85, 88, 36],
       [87, 91, 93, 90]], dtype=int32)

np.append

The numpy.append() appends valus along the mentioned axis at the end of the array

In [5]:
# code
np.append(a,200)

array([ 48,  29,  27,  20,  38,  89,  63,  79,  13,  89,  38,   6,  68,
        83,  49, 200])

In [6]:
b


array([[34, 85, 87, 22],
       [87,  8, 88,  4],
       [16, 56, 15, 36],
       [31, 91, 51, 90],
       [80, 54, 93,  3],
       [67, 56, 79,  5]], dtype=int32)

In [7]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[34., 85., 87., 22.,  1.],
       [87.,  8., 88.,  4.,  1.],
       [16., 56., 15., 36.,  1.],
       [31., 91., 51., 90.,  1.],
       [80., 54., 93.,  3.,  1.],
       [67., 56., 79.,  5.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [8]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique

with the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method


In [10]:
# code
e = np.array([11,22,2,2,3,3,5,6,9,4,8,8,8,0])

In [11]:
np.unique(e)

array([ 0,  2,  3,  4,  5,  6,  8,  9, 11, 22])

np.expand_dms

with the help Numpy.expand_dims() method, we can get the expanded dimension of an array


In [12]:
# code
a
a.shape

(15,)

In [13]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [14]:
np.expand_dims(a,axis=1)

array([[48],
       [29],
       [27],
       [20],
       [38],
       [89],
       [63],
       [79],
       [13],
       [89],
       [38],
       [ 6],
       [68],
       [83],
       [49]], dtype=int32)

np.where

The numpy.where() function return the indices of elements in an input array where the given condition is satisfied

In [15]:
a

array([48, 29, 27, 20, 38, 89, 63, 79, 13, 89, 38,  6, 68, 83, 49],
      dtype=int32)

In [16]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 5,  6,  7,  9, 12, 13]),)

In [ ]:
# replace aall values >50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

array([48, 29, 27, 20, 38,  0,  0,  0, 13,  0, 38,  6,  0,  0, 49],
      dtype=int32)

In [18]:
np.where(a %2 ==0,0,a)

array([ 0, 29, 27,  0,  0, 89, 63, 79, 13, 89,  0,  0,  0, 83, 49],
      dtype=int32)

np.argmax

The numpy.argmax() function return indices of the max element of the array in a particular axis

In [19]:
a

array([48, 29, 27, 20, 38, 89, 63, 79, 13, 89, 38,  6, 68, 83, 49],
      dtype=int32)

In [20]:
np.argmax(a)

np.int64(5)

In [21]:
b

array([[34, 85, 87, 22],
       [87,  8, 88,  4],
       [16, 56, 15, 36],
       [31, 91, 51, 90],
       [80, 54, 93,  3],
       [67, 56, 79,  5]], dtype=int32)

In [22]:
np.argmax(b,axis=0)

array([1, 3, 4, 3])

In [24]:
np.argmax(b,axis=1)

array([2, 2, 1, 1, 2, 2])

In [25]:
# np.argmin
np.argmin(a)

np.int64(11)

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [26]:
a

array([48, 29, 27, 20, 38, 89, 63, 79, 13, 89, 38,  6, 68, 83, 49],
      dtype=int32)

In [27]:
np.cumsum(a)

array([ 48,  77, 104, 124, 162, 251, 314, 393, 406, 495, 533, 539, 607,
       690, 739])

In [28]:
b

array([[34, 85, 87, 22],
       [87,  8, 88,  4],
       [16, 56, 15, 36],
       [31, 91, 51, 90],
       [80, 54, 93,  3],
       [67, 56, 79,  5]], dtype=int32)

In [29]:
np.cumsum(b)

array([  34,  119,  206,  228,  315,  323,  411,  415,  431,  487,  502,
        538,  569,  660,  711,  801,  881,  935, 1028, 1031, 1098, 1154,
       1233, 1238])

In [30]:
np.cumsum(b,axis=1)

array([[ 34, 119, 206, 228],
       [ 87,  95, 183, 187],
       [ 16,  72,  87, 123],
       [ 31, 122, 173, 263],
       [ 80, 134, 227, 230],
       [ 67, 123, 202, 207]])

In [31]:
# np.cumprod

np.cumprod(a)

array([                  48,                 1392,                37584,
                     751680,             28563840,           2542181760,
               160157450880,       12652438619520,      164481702053760,
          14638871482784640,   556277116345816320,  3337662698074897920,
        5600134584578439168,  3642568677271660544, -5981575550784149504])

np.percentile

numpy.percentile() function used to compute the nth percentile of the given data along the specificed axis

In [32]:
a

array([48, 29, 27, 20, 38, 89, 63, 79, 13, 89, 38,  6, 68, 83, 49],
      dtype=int32)

In [35]:
np.percentile(a,50)

np.float64(48.0)

In [36]:
np.median(a)

np.float64(48.0)

np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of the data distribution in the graphical form


In [37]:
a

array([48, 29, 27, 20, 38, 89, 63, 79, 13, 89, 38,  6, 68, 83, 49],
      dtype=int32)

In [38]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 3, 2, 2, 0, 2, 1, 3, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [39]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

np.corrcoef
 

Return person product-moment correlation coefficients.

In [40]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])