In [39]:
# np.array
import numpy as np

# a = np.array([1,2,3])
# print(a)

In [40]:
# 2D and 3D
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [41]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,5,8]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 5 8]]]


In [42]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [43]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
# np.ones np.zeros
np.ones((3,4))
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
# np.random
np.random.random(4)

array([0.14169334, 0.60719745, 0.94370139, 0.72732573])

In [47]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [48]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [49]:
a1 = np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [50]:
a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
# ndim
a3.ndim

3

In [52]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
# size
a3.size

8

In [54]:
# itemsize
a3.itemsize

8

In [55]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


Changing Datatype

In [56]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [57]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [58]:
# scaler operations

# arthematic
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [59]:
# relational 
a2 > 5
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [60]:
# vector operations
# arthematic
a1 + a2 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions

In [61]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 62.,   2., 100.],
       [ 94.,  88.,  79.],
       [ 30.,  36.,  52.]])

In [62]:
# min/max/sum/prod
# 0 -> col and 1-> row
np.max(a1)
np.sum(a1)
np.prod(a1)
np.max(a1,axis =0)

array([ 94.,  88., 100.])

In [63]:
# mean/median/std/var
np.mean(a1, axis = 1)
np.median(a1)
np.std(a1)
np.var(a1)

np.float64(978.6666666666666)

In [64]:
# trignometric function
np.sin(a1)

array([[-0.7391807 ,  0.90929743, -0.50636564],
       [-0.24525199,  0.0353983 , -0.44411267],
       [-0.98803162, -0.99177885,  0.98662759]])

In [66]:
# dot product
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [67]:
# log and exponents
np.log(a1)
np.exp(a1)

C:\Users\rahul\AppData\Local\Temp\ipykernel_20452\1488485187.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [71]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)



array([[72., 46., 48.],
       [55., 19., 60.]])

Indexing and Slicing

In [73]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [74]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a1[-1]

np.int64(9)

In [76]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a2[1,2]

np.int64(6)

In [80]:
a2[2,3]


np.int64(11)

In [83]:
a2[1,0]

np.int64(4)

In [85]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [86]:
a3[1,0,1]

np.int64(5)

In [88]:
a3[0,1,1]

np.int64(3)

In [89]:
a3[0,0,0]

np.int64(0)

In [90]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a1[2:5]

array([2, 3, 4])

In [92]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a2[0,:]

array([0, 1, 2, 3])

In [94]:
a2[:,2]

array([ 2,  6, 10])

In [95]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [97]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [105]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [106]:
a2[1,::3]

array([4, 7])

In [113]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [116]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [117]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [118]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [120]:
a3[0,1,:]

array([3, 4, 5])

In [122]:
a3[1,:,1]

array([10, 13, 16])

In [123]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [124]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [125]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [128]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [129]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [130]:
for i in a3:
    print(i)    

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [131]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [132]:
# reshape

In [135]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [136]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [137]:
# ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [138]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [141]:
# horizontal stacking
a4=np.arange(12).reshape(3, 4)
a5=np.arange(12,24).reshape(3, 4)
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [142]:
np.hstack((a4, a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [143]:
# vertical stacking
np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [144]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [146]:
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [149]:
# vertical splitting
np.vsplit(a4, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]