    np.sort

Return a sorted copy of an array


In [1]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[97, 47, 71, 43],
       [34, 86, 16, 70],
       [89, 48, 16, 63],
       [88, 90, 70, 19],
       [98, 95, 17, 65],
       [80, 78, 68, 81]])

In [3]:
np.sort(a)

array([ 2, 12, 19, 32, 50, 62, 63, 73, 73, 80, 89, 90, 94, 97, 97])

In [68]:
np.sort(b,axis=1)

array([[43, 47, 71, 97],
       [16, 34, 70, 86],
       [16, 48, 63, 89],
       [19, 70, 88, 90],
       [17, 65, 95, 98],
       [68, 78, 80, 81]])

np.append

The numpy.append() appends valus along the mentioned axis at the end of the array

In [69]:
# code
np.append(a,200)

array([100, 200,  80,  97,  12,  32,  90,  89,  97,  63,  73,  19,  62,
         2,  94, 200])

In [6]:
b


array([[97, 47, 71, 43],
       [34, 86, 16, 70],
       [89, 48, 16, 63],
       [88, 90, 70, 19],
       [98, 95, 17, 65],
       [80, 78, 68, 81]])

In [91]:
# np.ones()
np.ones((b.shape[0],2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [87]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[97., 47., 71., 43.,  1.],
       [34., 86., 16., 70.,  1.],
       [89., 48., 16., 63.,  1.],
       [88., 90., 70., 19.,  1.],
       [98., 95., 17., 65.,  1.],
       [80., 78., 68., 81.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [8]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [96]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique

with the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method


In [10]:
# code
e = np.array([11,22,2,2,3,3,5,6,9,4,8,8,8,0])

In [11]:
np.unique(e)

array([ 0,  2,  3,  4,  5,  6,  8,  9, 11, 22])

np.expand_dms

with the help Numpy.expand_dims() method, we can get the expanded dimension of an array


In [97]:
# code
a
a.shape

(15,)

In [13]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [99]:
np.expand_dims(a,axis=1)

array([[100],
       [200],
       [ 80],
       [ 97],
       [ 12],
       [ 32],
       [ 90],
       [ 89],
       [ 97],
       [ 63],
       [ 73],
       [ 19],
       [ 62],
       [  2],
       [ 94]])

np.where

The numpy.where() function return the indices of elements in an input array where the given condition is satisfied

In [15]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [16]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  3,  6,  7,  8,  9, 10, 12, 14], dtype=int64),)

In [17]:
# replace aall values >50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

array([ 0, 50,  0,  0, 12, 32,  0,  0,  0,  0,  0, 19,  0,  2,  0])

In [18]:
np.where(a %2 ==0,0,a)

array([73,  0,  0, 97,  0,  0,  0, 89, 97, 63, 73, 19,  0,  0,  0])

np.argmax

The numpy.argmax() function return indices of the max element of the array in a particular axis

In [19]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [20]:
np.argmax(a)

3

In [21]:
b

array([[97, 47, 71, 43],
       [34, 86, 16, 70],
       [89, 48, 16, 63],
       [88, 90, 70, 19],
       [98, 95, 17, 65],
       [80, 78, 68, 81]])

In [22]:
np.argmax(b,axis=0)

array([4, 4, 0, 5], dtype=int64)

In [23]:
np.argmax(b,axis=1)

array([0, 1, 0, 1, 0, 3], dtype=int64)

In [24]:
# np.argmin
np.argmin(a)

13

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [25]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [26]:
np.cumsum(a)

array([ 73, 123, 203, 300, 312, 344, 434, 523, 620, 683, 756, 775, 837,
       839, 933])

In [27]:
b

array([[97, 47, 71, 43],
       [34, 86, 16, 70],
       [89, 48, 16, 63],
       [88, 90, 70, 19],
       [98, 95, 17, 65],
       [80, 78, 68, 81]])

In [28]:
np.cumsum(b)

array([  97,  144,  215,  258,  292,  378,  394,  464,  553,  601,  617,
        680,  768,  858,  928,  947, 1045, 1140, 1157, 1222, 1302, 1380,
       1448, 1529])

In [29]:
np.cumsum(b,axis=1)

array([[ 97, 144, 215, 258],
       [ 34, 120, 136, 206],
       [ 89, 137, 153, 216],
       [ 88, 178, 248, 267],
       [ 98, 193, 210, 275],
       [ 80, 158, 226, 307]])

In [30]:
# np.cumprod

np.cumprod(a)

array([         73,        3650,      292000,    28324000,   339888000,
       -2008485888,  -375103488,   975527936,   136929280,    36610048,
       -1622433792,  -761470976,    33439744,    66879488,  1991704576])

np.percentile

numpy.percentile() function used to compute the nth percentile of the given data along the specificed axis

In [31]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [32]:
np.percentile(a,50)

73.0

In [33]:
np.median(a)

73.0

np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of the data distribution in the graphical form


In [34]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [35]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 0, 1, 0, 1, 2, 2, 2, 4], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [36]:
np.histogram(a,bins=[0,50,100])

(array([ 4, 11], dtype=int64), array([  0,  50, 100]))

np.corrcoef
 

Return person product-moment correlation coefficients.

In [37]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

with the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.


In [38]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [39]:
items = [10,20,30,6,40,5]

np.isin(a,items)
# which element is present 
a[np.isin(a,items)]

array([], dtype=int32)

np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [40]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [41]:
np.flip(a)

array([94,  2, 62, 19, 73, 63, 97, 89, 90, 32, 12, 97, 80, 50, 73])

In [42]:
b

array([[97, 47, 71, 43],
       [34, 86, 16, 70],
       [89, 48, 16, 63],
       [88, 90, 70, 19],
       [98, 95, 17, 65],
       [80, 78, 68, 81]])

In [43]:
np.flip(b)

array([[81, 68, 78, 80],
       [65, 17, 95, 98],
       [19, 70, 90, 88],
       [63, 16, 48, 89],
       [70, 16, 86, 34],
       [43, 71, 47, 97]])

In [44]:
np.flip(b,axis=0)

array([[80, 78, 68, 81],
       [98, 95, 17, 65],
       [88, 90, 70, 19],
       [89, 48, 16, 63],
       [34, 86, 16, 70],
       [97, 47, 71, 43]])

np.put 

The numpy.put() function replaces specific elements of an array with give values of p_array. Array indexed works on flattened array.

In [45]:
a

array([73, 50, 80, 97, 12, 32, 90, 89, 97, 63, 73, 19, 62,  2, 94])

In [46]:
np.put(a,[0,1],[100,200])

np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned aixis.

In [47]:
np.delete(a,0)

array([200,  80,  97,  12,  32,  90,  89,  97,  63,  73,  19,  62,   2,
        94])

In [48]:
np.delete(a,[1,2,3])

array([100,  12,  32,  90,  89,  97,  63,  73,  19,  62,   2,  94])

Set function

. np.union1d,
. np.intersect1d,
. np.setdiff1d,
. np.setxor1d,
. np.in11d

In [49]:
m = np.array([1,2,3,4,5])
n = np.array([4,5,6,7,8])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
np.intersect1d(m,n)

array([4, 5])

In [51]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [52]:
np.setdiff1d(n,m)

array([6, 7, 8])

In [53]:
np.setxor1d(m,n)

array([1, 2, 3, 6, 7, 8])

In [54]:
np.in1d(m,1)

array([ True, False, False, False, False])

In [55]:
m[np.in1d(m,1)]

array([1])

np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

In [56]:
a

array([100, 200,  80,  97,  12,  32,  90,  89,  97,  63,  73,  19,  62,
         2,  94])

In [57]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 25, 32, 75, 75, 75, 63, 73, 25, 62, 25, 75])