             np.sort

Return a sorted copy of an array


In [1]:
# code 
import numpy as np
a = np.random.randint(1,100,15)
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 2, 59, 16, 70],
       [33, 10, 19,  7],
       [38, 15, 98,  1],
       [50, 67, 63, 85],
       [49, 53, 78, 44],
       [29, 43, 36, 60]], dtype=int32)

In [3]:
np.sort(a)

array([ 4,  6, 13, 15, 17, 24, 31, 52, 56, 67, 76, 83, 85, 86, 89],
      dtype=int32)

In [4]:
np.sort(b,axis=0)

array([[ 2, 10, 16,  1],
       [29, 15, 19,  7],
       [33, 43, 36, 44],
       [38, 53, 63, 60],
       [49, 59, 78, 70],
       [50, 67, 98, 85]], dtype=int32)

np.append

The numpy.append() appends valus along the mentioned axis at the end of the array

In [5]:
# code
np.append(a,200)

array([ 76,  67,  56,  85,  31,   4,  17,  89,  86,   6,  24,  52,  15,
        13,  83, 200])

In [6]:
b


array([[ 2, 59, 16, 70],
       [33, 10, 19,  7],
       [38, 15, 98,  1],
       [50, 67, 63, 85],
       [49, 53, 78, 44],
       [29, 43, 36, 60]], dtype=int32)

In [7]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 2., 59., 16., 70.,  1.],
       [33., 10., 19.,  7.,  1.],
       [38., 15., 98.,  1.,  1.],
       [50., 67., 63., 85.,  1.],
       [49., 53., 78., 44.,  1.],
       [29., 43., 36., 60.,  1.]])

np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis

In [8]:
# code 
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

np.unique

with the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method


In [10]:
# code
e = np.array([11,22,2,2,3,3,5,6,9,4,8,8,8,0])

In [11]:
np.unique(e)

array([ 0,  2,  3,  4,  5,  6,  8,  9, 11, 22])

np.expand_dms

with the help Numpy.expand_dims() method, we can get the expanded dimension of an array


In [12]:
# code
a
a.shape

(15,)

In [13]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [14]:
np.expand_dims(a,axis=1)

array([[76],
       [67],
       [56],
       [85],
       [31],
       [ 4],
       [17],
       [89],
       [86],
       [ 6],
       [24],
       [52],
       [15],
       [13],
       [83]], dtype=int32)

np.where

The numpy.where() function return the indices of elements in an input array where the given condition is satisfied

In [15]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [16]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  3,  7,  8, 11, 14]),)

In [17]:
# replace aall values >50 with 0
# np.where(condition,True,False)
np.where(a>50,0,a)

array([ 0,  0,  0,  0, 31,  4, 17,  0,  0,  6, 24,  0, 15, 13,  0],
      dtype=int32)

In [18]:
np.where(a %2 ==0,0,a)

array([ 0, 67,  0, 85, 31,  0, 17, 89,  0,  0,  0,  0, 15, 13, 83],
      dtype=int32)

np.argmax

The numpy.argmax() function return indices of the max element of the array in a particular axis

In [19]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [20]:
np.argmax(a)

np.int64(7)

In [21]:
b

array([[ 2, 59, 16, 70],
       [33, 10, 19,  7],
       [38, 15, 98,  1],
       [50, 67, 63, 85],
       [49, 53, 78, 44],
       [29, 43, 36, 60]], dtype=int32)

In [22]:
np.argmax(b,axis=0)

array([3, 3, 2, 3])

In [23]:
np.argmax(b,axis=1)

array([3, 0, 2, 3, 2, 3])

In [24]:
# np.argmin
np.argmin(a)

np.int64(5)

np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [25]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [26]:
np.cumsum(a)

array([ 76, 143, 199, 284, 315, 319, 336, 425, 511, 517, 541, 593, 608,
       621, 704])

In [27]:
b

array([[ 2, 59, 16, 70],
       [33, 10, 19,  7],
       [38, 15, 98,  1],
       [50, 67, 63, 85],
       [49, 53, 78, 44],
       [29, 43, 36, 60]], dtype=int32)

In [28]:
np.cumsum(b)

array([   2,   61,   77,  147,  180,  190,  209,  216,  254,  269,  367,
        368,  418,  485,  548,  633,  682,  735,  813,  857,  886,  929,
        965, 1025])

In [29]:
np.cumsum(b,axis=1)

array([[  2,  61,  77, 147],
       [ 33,  43,  62,  69],
       [ 38,  53, 151, 152],
       [ 50, 117, 180, 265],
       [ 49, 102, 180, 224],
       [ 29,  72, 108, 168]])

In [30]:
# np.cumprod

np.cumprod(a)

array([                 76,                5092,              285152,
                  24237920,           751375520,          3005502080,
               51093535360,       4547324647040,     391069919645440,
          2346419517872640,   56314068428943360, 2928331558305054720,
       7031485227156717568, -824412415510429696, 5360745807472541696])

np.percentile

numpy.percentile() function used to compute the nth percentile of the given data along the specificed axis

In [31]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [32]:
np.percentile(a,50)

np.float64(52.0)

In [33]:
np.median(a)

np.float64(52.0)

np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of the data distribution in the graphical form


In [34]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [35]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([2, 3, 1, 1, 0, 2, 1, 1, 4, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [36]:
np.histogram(a,bins=[0,50,100])

(array([7, 8]), array([  0,  50, 100]))

np.corrcoef
 

Return person product-moment correlation coefficients.

In [37]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

with the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.


In [38]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [39]:
items = [10,20,30,6,40,5]

np.isin(a,items)
# which element is present 
a[np.isin(a,items)]

array([6], dtype=int32)

np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

In [40]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [41]:
np.flip(a)

array([83, 13, 15, 52, 24,  6, 86, 89, 17,  4, 31, 85, 56, 67, 76],
      dtype=int32)

In [42]:
b

array([[ 2, 59, 16, 70],
       [33, 10, 19,  7],
       [38, 15, 98,  1],
       [50, 67, 63, 85],
       [49, 53, 78, 44],
       [29, 43, 36, 60]], dtype=int32)

In [43]:
np.flip(b)

array([[60, 36, 43, 29],
       [44, 78, 53, 49],
       [85, 63, 67, 50],
       [ 1, 98, 15, 38],
       [ 7, 19, 10, 33],
       [70, 16, 59,  2]], dtype=int32)

In [44]:
np.flip(b,axis=0)

array([[29, 43, 36, 60],
       [49, 53, 78, 44],
       [50, 67, 63, 85],
       [38, 15, 98,  1],
       [33, 10, 19,  7],
       [ 2, 59, 16, 70]], dtype=int32)

np.put 

The numpy.put() function replaces specific elements of an array with give values of p_array. Array indexed works on flattened array.

In [45]:
a

array([76, 67, 56, 85, 31,  4, 17, 89, 86,  6, 24, 52, 15, 13, 83],
      dtype=int32)

In [46]:
np.put(a,[0,1],[100,200])

np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned aixis.

In [47]:
np.delete(a,0)

array([200,  56,  85,  31,   4,  17,  89,  86,   6,  24,  52,  15,  13,
        83], dtype=int32)

In [48]:
np.delete(a,[1,2,3])

array([100,  31,   4,  17,  89,  86,   6,  24,  52,  15,  13,  83],
      dtype=int32)

Set function

. np.union1d,
. np.intersect1d,
. np.setdiff1d,
. np.setxor1d,
. np.in11d

In [49]:
m = np.array([1,2,3,4,5])
n = np.array([4,5,6,7,8])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
np.intersect1d(m,n)

array([4, 5])

In [51]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [52]:
np.setdiff1d(n,m)

array([6, 7, 8])

In [53]:
np.setxor1d(m,n)

array([1, 2, 3, 6, 7, 8])

In [54]:
np.in1d(m,1)

C:\Users\rahul\AppData\Local\Temp\ipykernel_8436\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

In [55]:
m[np.in1d(m,1)]

C:\Users\rahul\AppData\Local\Temp\ipykernel_8436\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

In [56]:
a

array([100, 200,  56,  85,  31,   4,  17,  89,  86,   6,  24,  52,  15,
        13,  83], dtype=int32)

In [57]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 56, 75, 31, 25, 25, 75, 75, 25, 25, 52, 25, 25, 75],
      dtype=int32)